#Script by Leonardo Malaquias
# Create to Stephany Lazo

# Estimativa de Receitas e Despesas com compensação previdenciária

rm(list=ls())

# BIBLIOTECAS
library(readxl)
library(tidyverse)
library(lubridate)
library(forecast)
library(stats)

# BANCOS DE DADOS RGPS
RECEITA = read_excel("Z:/GERENCIA/DEMANDAS/2024/13.GCOMPREV/02. FONTES/1 - BASE DE DADOS UTILIZADAS/Série Histórica - RO x RI - v4.xlsx", 
                     sheet = "RO - Receita")

DESPESA = read_excel("Z:/GERENCIA/DEMANDAS/2024/13.GCOMPREV/02. FONTES/1 - BASE DE DADOS UTILIZADAS/Série Histórica - RO x RI - v4.xlsx", 
                     sheet = "RI - Despesa")
                                        
RECEITA$c

class(RGPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS)
dados$INPC = as.numeric(dados$INPC)

View(dados)


analise = function(base, coluna){

  
  
}

#------------------------------------------------------------------------------#
# Quantitativo do RGPS
# Despesa
TOTAL_VALOR_DESPESA.RGPS = sum(RGPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA)
TOTAL_DESPESA.RGPS = sum(RGPS_ENVIADOS.PARA.RPPS.GO$DESPESA)
TOTAL_ENVIADOS_DESPESA.RGPS = sum(RGPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS)

MEDIA_VALOR_DESPESA.RGPS = round(mean(RGPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA), 2)
MEDIA_DESPESA.RGPS = round(mean(RGPS_ENVIADOS.PARA.RPPS.GO$DESPESA), 2)
MEDIA_ENVIADOS_DESPESA.RGPS = round(mean(RGPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS), 2)

DESVIO_VALOR_DESPESA.RGPS = round(sd(RGPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA), 2)
DESVIO_DESPESA.RGPS = round(sd(RGPS_ENVIADOS.PARA.RPPS.GO$DESPESA), 2)
DESVIO_ENVIADOS_DESPESA.RGPS = round(sd(RGPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS), 2)

# Receita
TOTAL_VALOR_RECEITA.RGPS = sum(RGPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA)
TOTAL_RECEITA.RGPS = sum(RGPS_ENVIADOS.PELO.RPPS.GO$RECEITA)
TOTAL_ENVIADOS_RECEITA.RGPS = sum(RGPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS)

MEDIA_VALOR_RECEITA.RGPS = round(mean(RGPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA), 2)
MEDIA_RECEITA.RGPS = round(mean(RGPS_ENVIADOS.PELO.RPPS.GO$RECEITA), 2)
MEDIA_ENVIADOS_RECEITA.RGPS = round(mean(RGPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS), 2)

DESVIO_VALOR_RECEITA.RGPS = round(sd(RGPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA), 2)
DESVIO_RECEITA.RGPS = round(sd(RGPS_ENVIADOS.PELO.RPPS.GO$RECEITA), 2)
DESVIO_ENVIADOS_RECEITA.RGPS = round(sd(RGPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS), 2)

# Acumulado

ACUMULADO_RGPS.MENSAL = left_join(RGPS_ENVIADOS.PELO.RPPS.GO, RGPS_ENVIADOS.PARA.RPPS.GO, by = "COMPETENCIA") %>%
  mutate(ACUMULADO_RGPS.MENSAL = RECEITA - DESPESA) %>% 
  select(COMPETENCIA, ACUMULADO_RGPS.MENSAL)

ACUMULADO_RGPS.ANUAL = left_join(RGPS_ENVIADOS.PELO.RPPS.GO, RGPS_ENVIADOS.PARA.RPPS.GO, by = "COMPETENCIA") %>%
  mutate(ANO = lubridate::year(COMPETENCIA), ACUMULADO_RGPS.ANUAL = RECEITA - DESPESA) %>%
  group_by(ANO) %>%
  summarise(ACUMULADO_RGPS.ANUAL = sum(ACUMULADO_RGPS.ANUAL = RECEITA - DESPESA))

ACUMULADO_RGPS.GERAL = sum(ACUMULADO_RGPS.ANUAL$ACUMULADO_RGPS.ANUAL)

#------------------------------------------------------------------------------#
# Quantitativo do RPPS
# Despesa 
TOTAL_VALOR_DESPESA.RPPS = sum(RPPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA)
TOTAL_DESPESA.RPPS = sum(RPPS_ENVIADOS.PARA.RPPS.GO$DESPESA)
TOTAL_ENVIADOS_DESPESA.RPPS = sum(RPPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS)

MEDIA_VALOR_DESPESA.RPPS = round(mean(RPPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA), 2)
MEDIA_DESPESA.RPPS = round(mean(RPPS_ENVIADOS.PARA.RPPS.GO$DESPESA), 2)
MEDIA_ENVIADOS_DESPESA.RPPS = round(mean(RPPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS), 2)

DESVIO_VALOR_DESPESA.RPPS = round(sd(RPPS_ENVIADOS.PARA.RPPS.GO$VALOR_DESPESA), 2)
DESVIO_DESPESA.RPPS = round(sd(RPPS_ENVIADOS.PARA.RPPS.GO$DESPESA), 2)
DESVIO_ENVIADOS_DESPESA.RPPS = round(sd(RPPS_ENVIADOS.PARA.RPPS.GO$ENVIADOS), 2)

# Receita
TOTAL_VALOR_RECEITA.RPPS = sum(RPPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA)
TOTAL_RECEITA.RPPS = sum(RPPS_ENVIADOS.PELO.RPPS.GO$RECEITA)
TOTAL_ENVIADOS_RECEITA.RPPS = sum(RPPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS)

MEDIA_VALOR_RECEITA.RPPS = round(mean(RPPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA), 2)
MEDIA_RECEITA.RPPS = round(mean(RPPS_ENVIADOS.PELO.RPPS.GO$RECEITA), 2)
MEDIA_ENVIADOS_RECEITA.RPPS = round(mean(RPPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS), 2)

DESVIO_VALOR_RECEITA.RPPS = round(sd(RPPS_ENVIADOS.PELO.RPPS.GO$VALOR_RECEITA), 2)
DESVIO_RECEITA.RPPS = round(sd(RPPS_ENVIADOS.PELO.RPPS.GO$RECEITA), 2)
DESVIO_ENVIADOS_RECEITA.RPPS = round(sd(RPPS_ENVIADOS.PELO.RPPS.GO$ENVIADOS), 2)

# Acumulado

ACUMULADO_RPPS.MENSAL = left_join(RPPS_ENVIADOS.PELO.RPPS.GO, RPPS_ENVIADOS.PARA.RPPS.GO, by = "COMPETENCIA") %>%
  mutate(ACUMULADO_RPPS.MENSAL = RECEITA - DESPESA) %>% 
  select(COMPETENCIA, ACUMULADO_RPPS.MENSAL)

ACUMULADO_RPPS.ANUAL = left_join(RPPS_ENVIADOS.PELO.RPPS.GO, RPPS_ENVIADOS.PARA.RPPS.GO, by = "COMPETENCIA") %>%
  mutate(ANO = lubridate::year(COMPETENCIA), ACUMULADO_RPPS.ANUAL = RECEITA - DESPESA) %>%
  group_by(ANO) %>%
  summarise(ACUMULADO_RPPS.ANUAL = sum(ACUMULADO_RPPS.ANUAL = RECEITA - DESPESA))

ACUMULADO_RPPS.GERAL = sum(ACUMULADO_RPPS.ANUAL$ACUMULADO_RPPS.ANUAL)

#------------------------------------------------------------------------------#
# Ajustando o ARIMA - despesa rgps

DADOS.TS.ENVIADOS_DESPESA.RGPS = RGPS_ENVIADOS.PARA.RPPS.GO %>%
  mutate(APROVADOS = DESPESA - ENVIADOS) %>%
  select(COMPETENCIA, APROVADOS)
DADOS.TS.DESPESA.RGPS = ts(DADOS.TS.ENVIADOS_DESPESA.RGPS$APROVADOS, start = c(2012, 1), frequency = 12)

MODELO.DESPESA.RGPS = auto.arima(DADOS.TS.DESPESA.RGPS)
MODELO.DESPESA.RGPS_2 = HoltWinters(DADOS.TS.DESPESA.RGPS)
plot(DADOS.TS.DESPESA.RGPS)
lines(MODELO.DESPESA.RGPS$fitted, lty=2, col="red")
lines(MODELO.DESPESA.RGPS_2$fitted[,1], lty=2, col="blue")

PREVISAO.DESPESA.RGPS = forecast(MODELO.DESPESA.RGPS)
PREVISAO.DESPESA.RGPS_2 = forecast(MODELO.DESPESA.RGPS_2)
plot(PREVISAO.DESPESA.RGPS)
plot(PREVISAO.DESPESA.RGPS_2)



PREVISAO.DESPESA.DATAFRAME.RGPS = data.frame(`PREVISAO PONTUAL` = PREVISAO.DESPESA.RGPS$mean, PREVISAO.DESPESA.RGPS$lower, 
                                             PREVISAO.DESPESA.RGPS$upper)

#------------------------------------------------------------------------------#
# Ajustando o ARIMA - receita rgps

DADOS.TS.ENVIADOS_RECEITA.RGPS = RGPS_ENVIADOS.PELO.RPPS.GO %>%
  mutate(APROVADOS = RECEITA - ENVIADOS) %>%
  select(COMPETENCIA, APROVADOS)
DADOS.TS.RECEITA.RGPS = ts(DADOS.TS.ENVIADOS_RECEITA.RGPS$APROVADOS, start = c(2012, 1), frequency = 12)

MODELO.RECEITA.RGPS = auto.arima(DADOS.TS.RECEITA.RGPS)
MODELO.RECEITA.RGPS_2 = HoltWinters(DADOS.TS.RECEITA.RGPS)
plot(DADOS.TS.RECEITA.RGPS) 
lines(MODELO.RECEITA.RGPS$fitted, lty=2, col="red")
lines(MODELO.RECEITA.RGPS_2$fitted[,1], lty=2, col="blue")

PREVISAO.RECEITA.RGPS = forecast(MODELO.RECEITA.RGPS)
PREVISAO.RECEITA.RGPS_2 = forecast(MODELO.RECEITA.RGPS_2)
plot(PREVISAO.RECEITA.RGPS)   
plot(PREVISAO.RECEITA.RGPS_2)


PREVISAO.RECEITA.DATAFRAME.RGPS = data.frame(`PREVISAO PONTUAL` = PREVISAO.RECEITA.RGPS$mean, PREVISAO.RECEITA.RGPS$lower, 
                                             PREVISAO.RECEITA.RGPS$upper)

